version: '1.0'
services:
  db:
    image: mysql:8.0.37
    container_name: sprint3-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: CONCESIONARIO # Nombre de la base de datos que quieres crear
    volumes:
      - db_sprint3:/var/lib/mysql
    networks:
      - sprint3-net

  gestor:
    image: phpmyadmin
    container_name: sprint3-phpMyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db # El nombre del servicio db en la red
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: PASSWORD
    networks:
      - sprint3-net
volumes:
  db_sprint3:
networks:
  sprint3-net:
